#!/bin/bash
###############################################################################
# Filename:	mk-project-dir
# Description:	Create a directory structure for a new project. 
# Usage:	
#		mk-project-dir <project_name> <language>
# 

function create_c_directories {
	project_name=${1%/}
	mkdir -p $project_name/c/lib
	mkdir -p $project_name/c/bin
	mkdir -p $project_name/c/etc
	mkdir -p $project_name/c/src/build
	mkdir -p $project_name/c/share/doc
	mkdir -p $project_name/c/include
	if [ ! -f "$project_name/README.md" ]
	then
		echo "# $project_name" > $project_name/README.md
	fi
} # end create_c_directories()


if [ -z "$1" ]
then
	echo "ERROR: Please provide project name. Quitting."	
	exit
fi

if [ -z "$2" ]
then
	echo "ERROR: Please provide project language. Quitting."	
	exit
fi

case "$2" in
	c)
		create_c_directories $1
		;;
	*)
		echo "Language '$2' not recognised. Quitting."
		;;
esac


